/**
 * CIK Stores — Capability / Identity / Knowledge
 *
 * Three separate stores reflecting the CIK taxonomy (Wang et al., UCSC, 2026):
 *
 * - Capability: What the agent CAN do (tools, skills, learned procedures)
 * - Identity: WHO the agent is (DID, credentials, trust scores, reputation)
 * - Knowledge: What the agent KNOWS (facts, world model, learned information)
 *
 * Each store is:
 * - Independently governed by Cedar policies
 * - Cryptographically signed on every write (DID + Merkle)
 * - Isolated to prevent cross-contamination attacks (CIK taxonomy insight)
 */

import { randomUUID } from 'node:crypto';
import { sha256 } from '@odin/core';

// ─── Trust Tiers for Knowledge ───

export type TrustTier = 'T1' | 'T2' | 'T3' | 'T4';

/**
 * T1: User-declared (highest trust) — directly from the user
 * T2: Self-verified — agent verified through tool use / execution
 * T3: LLM-derived — generated by the model (may hallucinate)
 * T4: External-unverified — from external sources, not verified
 */
export const TRUST_TIER_CONFIDENCE: Record<TrustTier, number> = {
  T1: 1.0,
  T2: 0.85,
  T3: 0.6,
  T4: 0.3,
};

// ─── CIK Entry Types ───

export interface CapabilityEntry {
  id: string;
  name: string;
  type: 'tool' | 'skill' | 'procedure' | 'workflow';
  description: string;
  parameters?: Record<string, unknown>;
  learnedFrom?: string; // episode ID that taught this
  successRate: number; // 0.0-1.0
  usageCount: number;
  lastUsed: number;
  tier: TrustTier;
  merkleHash: string;
  createdAt: number;
  updatedAt: number;
}

export interface IdentityEntry {
  id: string;
  key: string; // e.g., "did", "trust_score", "credential:github", "reputation:agentlayers"
  value: string;
  type: 'did' | 'credential' | 'trust_score' | 'reputation' | 'preference' | 'relationship';
  issuer: string; // who set this value
  expiresAt?: number;
  tier: TrustTier;
  merkleHash: string;
  createdAt: number;
  updatedAt: number;
}

export interface KnowledgeEntry {
  id: string;
  subject: string;
  predicate: string;
  object: string;
  context?: string; // situational context
  source: string; // episode ID or "user:direct" or "tool:web_search"
  tier: TrustTier;
  confidence: number; // 0.0-1.0, initialized from tier, decays over time
  verifications: number; // how many times this was confirmed
  contradictions: number; // how many times this was contradicted
  merkleHash: string;
  createdAt: number;
  updatedAt: number;
}

// ─── Cedar-like Policy for CIK ───

export interface CIKPolicy {
  id: string;
  store: 'capability' | 'identity' | 'knowledge';
  action: 'read' | 'write' | 'delete' | 'evolve'; // evolve = upgrade tier
  effect: 'permit' | 'forbid';
  conditions: Array<{
    field: string;
    operator: 'eq' | 'neq' | 'gte' | 'lte' | 'in';
    value: unknown;
  }>;
}

// Default CIK policies
const DEFAULT_CIK_POLICIES: CIKPolicy[] = [
  // Knowledge: forbid writing T1 knowledge unless source is user
  {
    id: 'cik-knowledge-t1-write',
    store: 'knowledge',
    action: 'write',
    effect: 'forbid',
    conditions: [
      { field: 'tier', operator: 'eq', value: 'T1' },
      { field: 'source', operator: 'neq', value: 'user:direct' },
    ],
  },
  // Knowledge: forbid evolving from T4 directly to T1
  {
    id: 'cik-knowledge-no-skip-tier',
    store: 'knowledge',
    action: 'evolve',
    effect: 'forbid',
    conditions: [
      { field: 'currentTier', operator: 'eq', value: 'T4' },
      { field: 'targetTier', operator: 'eq', value: 'T1' },
    ],
  },
  // Identity: forbid modifying DID
  {
    id: 'cik-identity-did-immutable',
    store: 'identity',
    action: 'write',
    effect: 'forbid',
    conditions: [
      { field: 'key', operator: 'eq', value: 'did' },
      { field: 'exists', operator: 'eq', value: true },
    ],
  },
  // Capability: forbid deleting built-in tools
  {
    id: 'cik-capability-builtins',
    store: 'capability',
    action: 'delete',
    effect: 'forbid',
    conditions: [
      { field: 'type', operator: 'eq', value: 'tool' },
      { field: 'learnedFrom', operator: 'eq', value: undefined },
    ],
  },
];

export class CIKPolicyEngine {
  private policies: CIKPolicy[] = [...DEFAULT_CIK_POLICIES];

  addPolicy(policy: CIKPolicy): void {
    this.policies.push(policy);
  }

  evaluate(
    store: CIKPolicy['store'],
    action: CIKPolicy['action'],
    context: Record<string, unknown>,
  ): { allowed: boolean; reason: string; policyId: string } {
    // Find matching forbid policies
    for (const policy of this.policies) {
      if (policy.store !== store || policy.action !== action) continue;
      if (policy.effect !== 'forbid') continue;

      const allMatch = policy.conditions.every(cond => {
        const actual = context[cond.field];
        switch (cond.operator) {
          case 'eq': return actual === cond.value;
          case 'neq': return actual !== cond.value;
          case 'gte': return (actual as number) >= (cond.value as number);
          case 'lte': return (actual as number) <= (cond.value as number);
          case 'in': return (cond.value as unknown[]).includes(actual);
          default: return false;
        }
      });

      if (allMatch) {
        return { allowed: false, reason: `Denied by CIK policy ${policy.id}`, policyId: policy.id };
      }
    }

    return { allowed: true, reason: 'Permitted (no matching forbid)', policyId: 'default-permit' };
  }
}

// ─── CIK Store Manager ───

export class CIKStore {
  private db: any;
  private initialized = false;
  private policyEngine = new CIKPolicyEngine();

  constructor(private dbPath: string) {}

  async init(): Promise<void> {
    if (this.initialized) return;

    const Database = (await import('better-sqlite3')).default;
    this.db = new Database(this.dbPath);
    this.db.pragma('journal_mode = WAL');

    this.db.exec(`
      -- Capability store
      CREATE TABLE IF NOT EXISTS capabilities (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        type TEXT NOT NULL,
        description TEXT NOT NULL,
        parameters TEXT,
        learned_from TEXT,
        success_rate REAL NOT NULL DEFAULT 0.0,
        usage_count INTEGER NOT NULL DEFAULT 0,
        last_used INTEGER NOT NULL DEFAULT 0,
        tier TEXT NOT NULL DEFAULT 'T3',
        merkle_hash TEXT NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      );

      -- Identity store
      CREATE TABLE IF NOT EXISTS identity (
        id TEXT PRIMARY KEY,
        key TEXT NOT NULL UNIQUE,
        value TEXT NOT NULL,
        type TEXT NOT NULL,
        issuer TEXT NOT NULL,
        expires_at INTEGER,
        tier TEXT NOT NULL DEFAULT 'T1',
        merkle_hash TEXT NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      );

      -- Knowledge store (SPO triples with context)
      CREATE TABLE IF NOT EXISTS knowledge (
        id TEXT PRIMARY KEY,
        subject TEXT NOT NULL,
        predicate TEXT NOT NULL,
        object TEXT NOT NULL,
        context TEXT,
        source TEXT NOT NULL,
        tier TEXT NOT NULL DEFAULT 'T4',
        confidence REAL NOT NULL DEFAULT 0.3,
        verifications INTEGER NOT NULL DEFAULT 0,
        contradictions INTEGER NOT NULL DEFAULT 0,
        merkle_hash TEXT NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_knowledge_subject ON knowledge(subject);
      CREATE INDEX IF NOT EXISTS idx_knowledge_predicate ON knowledge(predicate);
      CREATE INDEX IF NOT EXISTS idx_knowledge_tier ON knowledge(tier);
      CREATE INDEX IF NOT EXISTS idx_knowledge_confidence ON knowledge(confidence);

      -- FTS for knowledge search
      CREATE VIRTUAL TABLE IF NOT EXISTS knowledge_fts USING fts5(
        id UNINDEXED, subject, predicate, object, context,
        tokenize='porter unicode61'
      );
    `);

    this.initialized = true;
  }

  // ─── CAPABILITY STORE ───

  async addCapability(entry: Omit<CapabilityEntry, 'id' | 'merkleHash' | 'createdAt' | 'updatedAt'>): Promise<CapabilityEntry | { error: string }> {
    await this.init();
    const check = this.policyEngine.evaluate('capability', 'write', { ...entry });
    if (!check.allowed) return { error: check.reason };

    const now = Date.now();
    const id = randomUUID();
    const merkleHash = sha256(JSON.stringify({ id, ...entry, timestamp: now }));

    this.db.prepare(`
      INSERT OR REPLACE INTO capabilities (id, name, type, description, parameters, learned_from, success_rate, usage_count, last_used, tier, merkle_hash, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(id, entry.name, entry.type, entry.description, JSON.stringify(entry.parameters ?? {}), entry.learnedFrom ?? null, entry.successRate, entry.usageCount, entry.lastUsed, entry.tier, merkleHash, now, now);

    return { id, ...entry, merkleHash, createdAt: now, updatedAt: now };
  }

  async getCapabilities(): Promise<CapabilityEntry[]> {
    await this.init();
    return (this.db.prepare('SELECT * FROM capabilities ORDER BY usage_count DESC').all() as any[]).map(r => ({
      id: r.id, name: r.name, type: r.type, description: r.description,
      parameters: JSON.parse(r.parameters ?? '{}'), learnedFrom: r.learned_from,
      successRate: r.success_rate, usageCount: r.usage_count, lastUsed: r.last_used,
      tier: r.tier, merkleHash: r.merkle_hash, createdAt: r.created_at, updatedAt: r.updated_at,
    }));
  }

  async recordCapabilityUsage(name: string, success: boolean): Promise<void> {
    await this.init();
    const now = Date.now();
    const row = this.db.prepare('SELECT * FROM capabilities WHERE name = ?').get(name) as any;
    if (!row) return;

    const newCount = row.usage_count + 1;
    const newRate = ((row.success_rate * row.usage_count) + (success ? 1 : 0)) / newCount;
    this.db.prepare('UPDATE capabilities SET usage_count = ?, success_rate = ?, last_used = ?, updated_at = ? WHERE name = ?')
      .run(newCount, newRate, now, now, name);
  }

  // ─── IDENTITY STORE ───

  async setIdentity(key: string, value: string, type: IdentityEntry['type'], issuer: string, tier: TrustTier = 'T1'): Promise<IdentityEntry | { error: string }> {
    await this.init();
    const existing = this.db.prepare('SELECT id, created_at FROM identity WHERE key = ?').get(key) as any;
    const check = this.policyEngine.evaluate('identity', 'write', { key, exists: !!existing, tier });
    if (!check.allowed) return { error: check.reason };

    const now = Date.now();
    const id = existing?.id ?? randomUUID();
    const merkleHash = sha256(JSON.stringify({ id, key, value, issuer, timestamp: now }));

    this.db.prepare(`
      INSERT OR REPLACE INTO identity (id, key, value, type, issuer, tier, merkle_hash, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(id, key, value, type, issuer, tier, merkleHash, existing ? existing.created_at : now, now);

    return { id, key, value, type, issuer, tier, merkleHash, createdAt: now, updatedAt: now };
  }

  async getIdentity(key: string): Promise<IdentityEntry | null> {
    await this.init();
    const row = this.db.prepare('SELECT * FROM identity WHERE key = ?').get(key) as any;
    if (!row) return null;
    return {
      id: row.id, key: row.key, value: row.value, type: row.type, issuer: row.issuer,
      expiresAt: row.expires_at, tier: row.tier, merkleHash: row.merkle_hash,
      createdAt: row.created_at, updatedAt: row.updated_at,
    };
  }

  async getAllIdentity(): Promise<IdentityEntry[]> {
    await this.init();
    return (this.db.prepare('SELECT * FROM identity ORDER BY key').all() as any[]).map(r => ({
      id: r.id, key: r.key, value: r.value, type: r.type, issuer: r.issuer,
      expiresAt: r.expires_at, tier: r.tier, merkleHash: r.merkle_hash,
      createdAt: r.created_at, updatedAt: r.updated_at,
    }));
  }

  // ─── KNOWLEDGE STORE ───

  async addKnowledge(
    subject: string, predicate: string, object: string,
    source: string, tier: TrustTier = 'T4', context?: string,
  ): Promise<KnowledgeEntry | { error: string }> {
    await this.init();
    const check = this.policyEngine.evaluate('knowledge', 'write', { tier, source });
    if (!check.allowed) return { error: check.reason };

    const confidence = TRUST_TIER_CONFIDENCE[tier];
    const now = Date.now();

    // Check for existing triple
    const existing = this.db.prepare(
      'SELECT * FROM knowledge WHERE subject = ? AND predicate = ? AND object = ?'
    ).get(subject, predicate, object) as any;

    if (existing) {
      // Reinforce
      const newVerifications = existing.verifications + 1;
      const newConf = Math.min(1.0, existing.confidence + 0.05);
      const merkleHash = sha256(JSON.stringify({ id: existing.id, verified: now }));
      this.db.prepare(
        'UPDATE knowledge SET verifications = ?, confidence = ?, updated_at = ?, merkle_hash = ? WHERE id = ?'
      ).run(newVerifications, newConf, now, merkleHash, existing.id);

      return {
        id: existing.id, subject, predicate, object, context: existing.context,
        source: existing.source, tier: existing.tier, confidence: newConf,
        verifications: newVerifications, contradictions: existing.contradictions,
        merkleHash, createdAt: existing.created_at, updatedAt: now,
      };
    }

    // Check for contradictions (same subject+predicate, different object)
    const contradicting = this.db.prepare(
      'SELECT id, object, confidence FROM knowledge WHERE subject = ? AND predicate = ? AND object != ?'
    ).all(subject, predicate, object) as any[];

    for (const c of contradicting) {
      // If new knowledge has higher tier confidence, mark old as contradicted
      if (confidence > c.confidence) {
        this.db.prepare('UPDATE knowledge SET contradictions = contradictions + 1, confidence = MAX(0.05, confidence - 0.1) WHERE id = ?').run(c.id);
      }
    }

    const id = randomUUID();
    const merkleHash = sha256(JSON.stringify({ id, subject, predicate, object, source, tier, timestamp: now }));

    this.db.prepare(`
      INSERT INTO knowledge (id, subject, predicate, object, context, source, tier, confidence, verifications, contradictions, merkle_hash, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?, ?, ?)
    `).run(id, subject, predicate, object, context ?? null, source, tier, confidence, merkleHash, now, now);

    this.db.prepare('INSERT INTO knowledge_fts (id, subject, predicate, object, context) VALUES (?, ?, ?, ?, ?)')
      .run(id, subject, predicate, object, context ?? '');

    return { id, subject, predicate, object, context, source, tier, confidence, verifications: 0, contradictions: 0, merkleHash, createdAt: now, updatedAt: now };
  }

  async queryKnowledge(query: string, minConfidence: number = 0.1, limit: number = 20): Promise<KnowledgeEntry[]> {
    await this.init();
    const sanitized = query.replace(/["\*\(\)\-\+\^~:]/g, ' ').trim();
    if (!sanitized) return [];
    const safeQuery = sanitized.split(/\s+/).map(t => `"${t}"`).join(' ');

    const rows = this.db.prepare(`
      SELECT k.* FROM knowledge_fts f JOIN knowledge k ON k.id = f.id
      WHERE knowledge_fts MATCH ? AND k.confidence >= ?
      ORDER BY k.confidence DESC, rank LIMIT ?
    `).all(safeQuery, minConfidence, limit) as any[];

    return rows.map(r => ({
      id: r.id, subject: r.subject, predicate: r.predicate, object: r.object,
      context: r.context, source: r.source, tier: r.tier, confidence: r.confidence,
      verifications: r.verifications, contradictions: r.contradictions,
      merkleHash: r.merkle_hash, createdAt: r.created_at, updatedAt: r.updated_at,
    }));
  }

  async getKnowledgeAbout(subject: string): Promise<KnowledgeEntry[]> {
    await this.init();
    const rows = this.db.prepare(
      'SELECT * FROM knowledge WHERE subject = ? ORDER BY confidence DESC'
    ).all(subject) as any[];

    return rows.map(r => ({
      id: r.id, subject: r.subject, predicate: r.predicate, object: r.object,
      context: r.context, source: r.source, tier: r.tier, confidence: r.confidence,
      verifications: r.verifications, contradictions: r.contradictions,
      merkleHash: r.merkle_hash, createdAt: r.created_at, updatedAt: r.updated_at,
    }));
  }

  /**
   * Evolve knowledge tier: T4 → T3 → T2 → T1
   * Requires verification evidence.
   */
  async evolveKnowledgeTier(
    knowledgeId: string, targetTier: TrustTier, evidence: string,
  ): Promise<{ success: boolean; message: string }> {
    await this.init();
    const row = this.db.prepare('SELECT * FROM knowledge WHERE id = ?').get(knowledgeId) as any;
    if (!row) return { success: false, message: 'Knowledge entry not found' };

    const check = this.policyEngine.evaluate('knowledge', 'evolve', {
      currentTier: row.tier, targetTier, source: row.source,
    });
    if (!check.allowed) return { success: false, message: check.reason };

    const tiers: TrustTier[] = ['T4', 'T3', 'T2', 'T1'];
    const currentIdx = tiers.indexOf(row.tier);
    const targetIdx = tiers.indexOf(targetTier);

    if (targetIdx <= currentIdx) {
      return { success: false, message: `Cannot evolve from ${row.tier} to ${targetTier} — must go one step at a time` };
    }
    if (targetIdx > currentIdx + 1) {
      return { success: false, message: `Cannot skip tiers — evolve from ${row.tier} to ${tiers[currentIdx + 1]} first` };
    }

    const newConf = TRUST_TIER_CONFIDENCE[targetTier];
    const now = Date.now();
    const merkleHash = sha256(JSON.stringify({ id: knowledgeId, evolved: targetTier, evidence, timestamp: now }));

    this.db.prepare('UPDATE knowledge SET tier = ?, confidence = ?, updated_at = ?, merkle_hash = ? WHERE id = ?')
      .run(targetTier, newConf, now, merkleHash, knowledgeId);

    return { success: true, message: `Knowledge evolved: ${row.tier} → ${targetTier}` };
  }

  getStats(): { capabilities: number; identity: number; knowledge: number; knowledgeByTier: Record<string, number> } {
    const c = this.db.prepare('SELECT COUNT(*) as c FROM capabilities').get() as any;
    const i = this.db.prepare('SELECT COUNT(*) as c FROM identity').get() as any;
    const k = this.db.prepare('SELECT COUNT(*) as c FROM knowledge').get() as any;
    const tiers = this.db.prepare('SELECT tier, COUNT(*) as c FROM knowledge GROUP BY tier').all() as any[];
    const byTier: Record<string, number> = {};
    for (const t of tiers) byTier[t.tier] = t.c;

    return { capabilities: c.c, identity: i.c, knowledge: k.c, knowledgeByTier: byTier };
  }

  getPolicyEngine(): CIKPolicyEngine { return this.policyEngine; }

  async close(): Promise<void> {
    if (this.db) { this.db.close(); this.initialized = false; }
  }
}
